name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  some-check:
    runs-on: ubuntu-latest
    outputs:
      should-merge: ${{ steps.some-check.outputs.should-merge }}
    steps:
      - name: Some check
        id: some-check
        run: echo "should-merge=true" >> $GITHUB_OUTPUT

  dependabot:
    needs: some-check
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }} && ${{ needs.some-check.outputs.should-merge == 'true' }}
    steps:
      - name: Auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
